export const ADD_POMODORO_TIME = "ADD_POMODORO_TIME";
export const AUTO_BREAK = "AUTO_BREAK";
export const SWITCH_COUNTER = "SWITCH_COUNTER";
export const SET_SELECTED_COUNTER = "SET_SELECTED_COUNTER";
export const FETCH_ITEMS = "FETCH_ITEMS";
